---
name: Release

on:
  push:
    tags:
      - "v*.*"

permissions:
  contents: write

jobs:
  packages:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
      # Option --privileged is required for mock+podman on fedora
      options: --privileged
    steps:
      - uses: actions/checkout@v4

      - name: Set version environment variable
        run: |
          _VERSION=${{ github.ref_name }}
          # Trim leading v prefix from tag
          echo RIFT_VERSION="${_VERSION:1}" >> "$GITHUB_ENV"

      - name: Build source tarball
        run: |
          mkdir -p ~/rpmbuild/SOURCES
          tar -czvf ~/rpmbuild/SOURCES/rift-${RIFT_VERSION}.tar.gz \
            -C ${GITHUB_WORKSPACE}/.. rift

      - name: Install mock
        run: |
          dnf install -y mock

      - name: Build source RPM
        run: |
          mock --verbose --root almalinux-8-x86_64 \
            --define "ci_version ${RIFT_VERSION}" \
            --buildsrpm \
            --sources ~/rpmbuild/SOURCES \
            --resultdir ~/rpmbuild/SRPMS \
            --spec rift.spec

      - name: Build binary RPM
        run: |
          mock --verbose --root almalinux-8-x86_64 \
            --define "ci_version ${RIFT_VERSION}" \
            --resultdir ~/rpmbuild/RPMS \
            ~/rpmbuild/SRPMS/rift*.src.rpm

      - name: Create release
        uses: softprops/action-gh-release@v2.5.0
        with:
          files: |
            /github/home/rpmbuild/RPMS/*.rpm
