---
name: Release

on:
  push:
    tags:
      - "v*.*"

permissions:
  contents: write

jobs:
  sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set version environment variable
        run: |
          _VERSION=${{ github.ref_name }}
          # Trim leading v prefix from tag
          echo RIFT_VERSION="${_VERSION:1}" >> "$GITHUB_ENV"

      - name: Build source tarball
        run: |
          mkdir -p ~/rpmbuild/SOURCES
          tar -czvf ~/rpmbuild/SOURCES/rift-${RIFT_VERSION}.tar.gz \
            -C ${GITHUB_WORKSPACE}/.. rift

  packages:
    needs: sources
    strategy:
      # Disable automatic cancellation of other running jobs as soon as one
      # failure occurs in the matrix.
      fail-fast: false
      matrix:
        buildenv:
        - almalinux-8-x86_64
        - almalinux-9-x86_64
        - fedora-43-x86_64

    runs-on: ubuntu-latest
    container:
      image: fedora:latest
      # Option --privileged is required for mock+podman on fedora
      options: --privileged
    steps:
      - name: Install mock
        run: |
          dnf install -y mock

      - name: Build source RPM
        run: |
          mock --verbose --root ${{ matrix.buildenv }} \
            --define "ci_version ${RIFT_VERSION}" \
            --buildsrpm \
            --sources ~/rpmbuild/SOURCES \
            --resultdir ~/rpmbuild/SRPMS \
            --spec rift.spec

      - name: Build binary RPM
        run: |
          mock --verbose --root ${{ matrix.buildenv }} \
            --define "ci_version ${RIFT_VERSION}" \
            --resultdir ~/rpmbuild/RPMS \
            ~/rpmbuild/SRPMS/rift*.src.rpm

  release:
    needs: packages
    runs-on: ubuntu-latest
    steps:
    - name: Create release
      uses: softprops/action-gh-release@v2.5.0
      with:
        files: |
          /github/home/rpmbuild/RPMS/*.rpm
